name: Build and Deploy to Review
on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Leave blank to use current HEAD, or provide an override commit SHA"
        type: string
        required: false

jobs:
  test:
    name: Test
    uses: ./.github/actions/test.yml

  deploy:
    name: Deploy
    needs: [test]
    uses: ./.github/workflows/build_and_deploy_generic.yml
    with:
      commit: ${{ inputs.commit }}
      environment: review
    secrets: inherit
