name: Deploy Interface to Production
on:
  workflow_dispatch:
    inputs:
      # commit hash (for frontend deploy to Amplify)
      commit:
        description: "Commit ref"
        required: true
        type: string
  workflow_call:
    inputs:
      commit:
        description: "Commit ref"
        required: true
        type: string

jobs:
  ui-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commit }}

      - name: Install UI dependencies
        working-directory: ./interface
        run: yarn --frozen-lockfile && yarn build

      - name: Run tests
        working-directory: ./interface
        run: yarn test

  deploy-app:
    needs: [ui-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commit }}

      - name: Checkout production-interface
        run: |
          git fetch
          git checkout -b production-interface origin/production-interface
          git reset --hard ${{ inputs.commit }}
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/gitcoinco/passport-scorer.git
          git push origin production-interface -f
