name: Deploy Interface to Review

on:
  push:
    branches: [mainXXX]

jobs:
  ui-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install UI dependencies
        working-directory: ./interface
        run: yarn --frozen-lockfile && yarn build

      - name: Run tests
        working-directory: ./interface
        run: yarn test

  deploy-app:
    needs: [ui-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout review-interface
        run: |
          git fetch
          git checkout -b review-interface origin/review-interface
          git reset --hard ${{ github.event.inputs.commit }}
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/gitcoinco/passport-scorer.git
          git push origin review-interface -f
